---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginxpm

labels:
  - pairs:
      app: nginxpm
    includeSelectors: true

resources:
  - namespace.yaml
  - pvc.yaml
  - nginxpm-deployment.yaml
  - nginxpm-service.yaml
