version: '3.8'
name: nginx-proxy-manager

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm-app
    ports:
      - "${NPM_HTTP_PORT:-80}:80"
      - "${NPM_HTTPS_PORT:-443}:443"
      - "${NPM_ADMIN_PORT:-81}:81"
    environment:
      - TZ=${TZ:-Asia/Taipei}
    volumes:
      - npm-app-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    restart: unless-stopped

volumes:
  npm-app-data:
    name: npm-app-data
  npm-letsencrypt:
    name: npm-letsencrypt
