---
apiVersion: v1
kind: Service
metadata:
  name: nginxpm
  namespace: nginxpm
  labels:
    app: nginxpm
spec:
  type: NodePort
  selector:
    app: nginxpm
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      nodePort: 30443
      protocol: TCP
    - name: admin-ui
      port: 81
      targetPort: admin-ui
      nodePort: 30081
      protocol: TCP
