---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxpm-data
  namespace: nginxpm
  labels:
    app: nginxpm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxpm-letsencrypt
  namespace: nginxpm
  labels:
    app: nginxpm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
